version: '3.8'

services:
  broker:
    build: .
    container_name: broker
    ports:
      - "1883:1883"    # Expose the TLS port 8883 for the broker or 1883 for MQTT w/out TLS
    networks:
      - iot-network
    environment:
      - ROLE=broker
    command: ["mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]

  client1:
    build: .
    container_name: Crew_1
    networks:
      - iot-network
    environment:
      - ROLE=client
    command: ["python3", "/app/CSMIM_Network/configured_clients/Crew_1/Client_v_1_5/client.py"]
    depends_on:
      - broker

  client2:
    build: .
    container_name: Light_1
    networks:
      - iot-network
    environment:
      - ROLE=client
    command: ["python3", "/app/CSMIM_Network/configured_clients/Light_1/Client_v_1_5/client.py"]
    depends_on:
      - broker

networks:
  iot-network:
    driver: bridge
